variables:
  PIPENV_VENV_IN_PROJECT: "true"

stages:
  - build
  - test
  - ship

image: python:3.8

whl:
  stage: build
  before_script:
    - pip install pipenv
    - pipenv lock -r > requirements.txt
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*

pytest:
  stage: test
  before_script:
    - pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run pytest
  cache:
    paths:
      - .venv/*
  except:
    - tags

pypi:
  stage: ship
  before_script:
    - pip install pipenv twine
    - pipenv lock -r > requirements.txt
  script:
    - python setup.py verify
    - TWINE_USERNAME="gitlab-ci-token" TWINE_PASSWORD="${CI_JOB_TOKEN}"
      python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  needs:
    - whl
  rules:
    - if: "$CI_COMMIT_TAG"
