variables:
  PIPENV_VENV_IN_PROJECT: "true"

stages:
  - build
  - test
  - ship

image: python:3.8

whl:
  stage: build
  before_script:
    - pip install pipenv
    - pipenv lock -r > requirements.txt
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*

pytest:
  stage: test
  services:
    - name: docker:dind
      # explicitly disable tls to avoid docker startup interruption
      command: [ "--tls=false" ]

  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    DOCKER_TLS_VERIFY: ""
    DOCKER_CERT_PATH: ""
  before_script:
    - pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run pytest
  cache:
    paths:
      - .venv/*
  except:
    - tags

pypi:
  stage: ship
  before_script:
    - pip install pipenv twine
    - pipenv lock -r > requirements.txt
  script:
    - python setup.py verify
    - TWINE_USERNAME="gitlab-ci-token" TWINE_PASSWORD="${CI_JOB_TOKEN}"
      python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  needs:
    - whl
  rules:
    - if: "$CI_COMMIT_TAG"
